# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Backup\coding\git\Github_Gen5_VR14\Gen5_VR14\PyQT_IFX_VR14.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 947)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("C:\\Backup\\coding\\git\\Github_Gen5_VR14\\Gen5_VR14\\IFX_LOGO_RGB.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 110, 801, 781))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 241, 131))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 63))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QtCore.QRect(120, 100, 111, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 741, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 721, 57))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 4, 2, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 1, 1, 1, 3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(450, 10, 301, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 21, 281, 101))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_3.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_3.addWidget(self.lineEdit_18, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_3.addWidget(self.lineEdit_19, 2, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 0, 2, 3, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QtCore.QRect(580, 520, 161, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(260, 10, 181, 131))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setGeometry(QtCore.QRect(80, 90, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 20, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setGeometry(QtCore.QRect(580, 460, 161, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setEnabled(False)
        self.checkBox_5.setGeometry(QtCore.QRect(580, 490, 111, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 230, 741, 221))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(640, 100, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(330, 30, 301, 181))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 5, 1, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 311, 181))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_5.addWidget(self.lineEdit_16, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_5.addWidget(self.lineEdit_6, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 5, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_5.addWidget(self.lineEdit_8, 5, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 460, 181, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setGeometry(QtCore.QRect(1, 40, 120, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setGeometry(QtCore.QRect(1, 90, 152, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setEnabled(False)
        self.label_15.setGeometry(QtCore.QRect(1, 21, 34, 16))
        self.label_15.setObjectName("label_15")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setGeometry(QtCore.QRect(1, 67, 161, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 460, 331, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 301, 91))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(580, 580, 171, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 633, 142))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_4.addWidget(self.lineEdit_20, 1, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_4.addWidget(self.lineEdit_21, 1, 3, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_4.addWidget(self.lineEdit_22, 1, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_4.addWidget(self.lineEdit_23, 2, 2, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_4.addWidget(self.lineEdit_24, 2, 3, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_4.addWidget(self.lineEdit_25, 2, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 3, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_4.addWidget(self.lineEdit_26, 3, 2, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_4.addWidget(self.lineEdit_27, 3, 3, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_4.addWidget(self.lineEdit_28, 3, 4, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 4, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_5, 4, 1, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_4.addWidget(self.lineEdit_29, 4, 2, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_4.addWidget(self.lineEdit_30, 4, 3, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_4.addWidget(self.lineEdit_31, 4, 4, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_4.addWidget(self.pushButton_10, 0, 5, 5, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 190, 771, 251))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_10)
        self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_11)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.horizontalLayout.addWidget(self.lineEdit_59)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.horizontalLayout.addWidget(self.lineEdit_60)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_2.addWidget(self.checkBox_7)
        self.comboBox_12 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_12)
        self.comboBox_13 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_13)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.horizontalLayout_2.addWidget(self.lineEdit_61)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.horizontalLayout_2.addWidget(self.lineEdit_62)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_3.addWidget(self.checkBox_8)
        self.comboBox_14 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_14)
        self.comboBox_15 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_15)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.horizontalLayout_3.addWidget(self.lineEdit_63)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.horizontalLayout_3.addWidget(self.lineEdit_64)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_4.addWidget(self.checkBox_9)
        self.comboBox_16 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_16)
        self.comboBox_17 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_17)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.horizontalLayout_4.addWidget(self.lineEdit_65)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.horizontalLayout_4.addWidget(self.lineEdit_66)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_17 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_17.setObjectName("checkBox_17")
        self.horizontalLayout_7.addWidget(self.checkBox_17)
        self.comboBox_18 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_18)
        self.comboBox_19 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_19)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.horizontalLayout_7.addWidget(self.lineEdit_67)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.horizontalLayout_7.addWidget(self.lineEdit_68)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_18 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_9.addWidget(self.checkBox_18)
        self.comboBox_21 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_21)
        self.comboBox_22 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_22)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.horizontalLayout_9.addWidget(self.lineEdit_69)
        self.lineEdit_70 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.horizontalLayout_9.addWidget(self.lineEdit_70)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_19 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout_8.addWidget(self.checkBox_19)
        self.comboBox_20 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_20)
        self.comboBox_37 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_37.setObjectName("comboBox_37")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_37)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.horizontalLayout_8.addWidget(self.lineEdit_71)
        self.lineEdit_72 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.horizontalLayout_8.addWidget(self.lineEdit_72)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(530, 170, 120, 12))
        self.label_36.setObjectName("label_36")
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setGeometry(QtCore.QRect(70, 170, 120, 12))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setGeometry(QtCore.QRect(300, 170, 120, 12))
        self.label_41.setObjectName("label_41")
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setGeometry(QtCore.QRect(210, 170, 120, 12))
        self.label_39.setObjectName("label_39")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(390, 710, 391, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_17.addWidget(self.label_37)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.horizontalLayout_17.addWidget(self.lineEdit_58)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_17.addWidget(self.label_38)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_17.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_17.addWidget(self.pushButton_13)
        self.layoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 440, 771, 251))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_10.addWidget(self.checkBox_10)
        self.comboBox_23 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_23)
        self.comboBox_24 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_24)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.horizontalLayout_10.addWidget(self.lineEdit_44)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.horizontalLayout_10.addWidget(self.lineEdit_45)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_11.addWidget(self.checkBox_11)
        self.comboBox_25 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_25)
        self.comboBox_26 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_26)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.horizontalLayout_11.addWidget(self.lineEdit_46)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.horizontalLayout_11.addWidget(self.lineEdit_47)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_12.addWidget(self.checkBox_12)
        self.comboBox_27 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_27)
        self.comboBox_28 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_28)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.horizontalLayout_12.addWidget(self.lineEdit_48)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.horizontalLayout_12.addWidget(self.lineEdit_49)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_13.addWidget(self.checkBox_13)
        self.comboBox_29 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_29)
        self.comboBox_30 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_30)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.horizontalLayout_13.addWidget(self.lineEdit_50)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.horizontalLayout_13.addWidget(self.lineEdit_51)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_14 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_14.addWidget(self.checkBox_14)
        self.comboBox_31 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_31)
        self.comboBox_32 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_32.setObjectName("comboBox_32")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_32)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.horizontalLayout_14.addWidget(self.lineEdit_52)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.horizontalLayout_14.addWidget(self.lineEdit_53)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_15 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_15.addWidget(self.checkBox_15)
        self.comboBox_33 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_33.setObjectName("comboBox_33")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_33)
        self.comboBox_34 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_34.setObjectName("comboBox_34")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_34)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.horizontalLayout_15.addWidget(self.lineEdit_54)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.horizontalLayout_15.addWidget(self.lineEdit_55)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBox_16 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout_16.addWidget(self.checkBox_16)
        self.comboBox_35 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_35.setObjectName("comboBox_35")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_35)
        self.comboBox_36 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_36.setObjectName("comboBox_36")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_36)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.horizontalLayout_16.addWidget(self.lineEdit_56)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.horizontalLayout_16.addWidget(self.lineEdit_57)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 26))
        self.menubar.setObjectName("menubar")
        self.menu2020_08_22 = QtWidgets.QMenu(self.menubar)
        self.menu2020_08_22.setObjectName("menu2020_08_22")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action2020_10 = QtWidgets.QAction(MainWindow)
        self.action2020_10.setObjectName("action2020_10")
        self.menu2020_08_22.addAction(self.action2020_10)
        self.menubar.addAction(self.menu2020_08_22.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IFX PyGUI"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Select your power rail"))
        self.label_17.setText(_translate("MainWindow", "Select power rail"))
        self.comboBox.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox.setItemText(4, _translate("MainWindow", "PVCCD_HV"))
        self.checkBox_2.setText(_translate("MainWindow", "Open by Excel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "DC LL line"))
        self.label_11.setText(_translate("MainWindow", "vout(V)"))
        self.lineEdit_10.setText(_translate("MainWindow", "1,0.8"))
        self.label_13.setText(_translate("MainWindow", "cool_down_delay(Sec)"))
        self.lineEdit_14.setText(_translate("MainWindow", "2"))
        self.pushButton_2.setText(_translate("MainWindow", "LoadLine tset"))
        self.label_12.setText(_translate("MainWindow", "iout list(A)"))
        self.lineEdit_11.setText(_translate("MainWindow", "10,20,30"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Thermal"))
        self.label_19.setText(_translate("MainWindow", "vout(V)"))
        self.lineEdit_17.setText(_translate("MainWindow", "1.83"))
        self.label_20.setText(_translate("MainWindow", "Iout(A)"))
        self.lineEdit_18.setText(_translate("MainWindow", "200"))
        self.label_21.setText(_translate("MainWindow", "Time(Sec)"))
        self.lineEdit_19.setText(_translate("MainWindow", "0,10,300,600"))
        self.pushButton_8.setText(_translate("MainWindow", "thermal drop"))
        self.pushButton_7.setText(_translate("MainWindow", "Abort test"))
        self.groupBox_6.setTitle(_translate("MainWindow", "check Vendor ID"))
        self.pushButton_9.setText(_translate("MainWindow", "Check"))
        self.checkBox_6.setText(_translate("MainWindow", "online LL and Imon curve"))
        self.checkBox_5.setText(_translate("MainWindow", "online 3D curve"))
        self.groupBox.setTitle(_translate("MainWindow", "3D parameter"))
        self.pushButton.setText(_translate("MainWindow", "Run 3D test"))
        self.label_16.setText(_translate("MainWindow", "cool_down_delay(Sec)"))
        self.lineEdit_15.setText(_translate("MainWindow", "2"))
        self.label_2.setText(_translate("MainWindow", "end_freq(KHz)"))
        self.lineEdit_2.setText(_translate("MainWindow", "1000"))
        self.label_14.setText(_translate("MainWindow", "fall_time(nSec)"))
        self.lineEdit_12.setText(_translate("MainWindow", "765"))
        self.label_3.setText(_translate("MainWindow", "icc_max(A)"))
        self.lineEdit_3.setText(_translate("MainWindow", "33"))
        self.label_9.setText(_translate("MainWindow", "duty_step(%)"))
        self.lineEdit_9.setText(_translate("MainWindow", "10"))
        self.label_8.setText(_translate("MainWindow", "end_duty(%)"))
        self.lineEdit_7.setText(_translate("MainWindow", "50"))
        self.label_18.setText(_translate("MainWindow", "vout(V)"))
        self.lineEdit_16.setText(_translate("MainWindow", "1,0.8"))
        self.label.setText(_translate("MainWindow", "start_freq(KHz)"))
        self.lineEdit.setText(_translate("MainWindow", "0.3"))
        self.label_6.setText(_translate("MainWindow", "rise_time(nSec)"))
        self.lineEdit_6.setText(_translate("MainWindow", "765"))
        self.label_4.setText(_translate("MainWindow", "icc_min(A)"))
        self.lineEdit_4.setText(_translate("MainWindow", "10"))
        self.label_5.setText(_translate("MainWindow", "freq_steps_per_decade"))
        self.lineEdit_5.setText(_translate("MainWindow", "9"))
        self.label_7.setText(_translate("MainWindow", "start_duty(%)"))
        self.lineEdit_8.setText(_translate("MainWindow", "10"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Misc"))
        self.lineEdit_13.setText(_translate("MainWindow", "file name"))
        self.checkBox_3.setText(_translate("MainWindow", "Filename includes timestamp"))
        self.label_15.setText(_translate("MainWindow", "Save to"))
        self.checkBox_4.setText(_translate("MainWindow", "Filename include rail and Vout"))
        self.groupBox_4.setTitle(_translate("MainWindow", "others"))
        self.pushButton_3.setText(_translate("MainWindow", "Open result folder"))
        self.pushButton_4.setText(_translate("MainWindow", "Open Result in GUI"))
        self.pushButton_5.setText(_translate("MainWindow", "save parameter to file"))
        self.pushButton_6.setText(_translate("MainWindow", "load parameter to GUI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "LoadLine and 3D"))
        self.label_22.setText(_translate("MainWindow", "WP1"))
        self.label_23.setText(_translate("MainWindow", "WP2"))
        self.label_24.setText(_translate("MainWindow", "Static Load"))
        self.label_25.setText(_translate("MainWindow", "Rail1"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.lineEdit_20.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_21.setText(_translate("MainWindow", "1.6"))
        self.lineEdit_22.setText(_translate("MainWindow", "3"))
        self.label_26.setText(_translate("MainWindow", "Rail2"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.lineEdit_23.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_24.setText(_translate("MainWindow", "1.6"))
        self.lineEdit_25.setText(_translate("MainWindow", "5"))
        self.label_27.setText(_translate("MainWindow", "Rail3"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.lineEdit_26.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_27.setText(_translate("MainWindow", "1.6"))
        self.lineEdit_28.setText(_translate("MainWindow", "4"))
        self.label_28.setText(_translate("MainWindow", "Rail3"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.lineEdit_29.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_30.setText(_translate("MainWindow", "1.6"))
        self.lineEdit_31.setText(_translate("MainWindow", "3"))
        self.pushButton_10.setText(_translate("MainWindow", "SetWP init"))
        self.checkBox.setText(_translate("MainWindow", "select"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_59.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_60.setText(_translate("MainWindow", "1.8"))
        self.checkBox_7.setText(_translate("MainWindow", "select"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_61.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_62.setText(_translate("MainWindow", "1.8"))
        self.checkBox_8.setText(_translate("MainWindow", "select"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_14.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_15.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_15.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_63.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_64.setText(_translate("MainWindow", "1.8"))
        self.checkBox_9.setText(_translate("MainWindow", "select"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_16.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_16.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_17.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_17.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_65.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_66.setText(_translate("MainWindow", "1.8"))
        self.checkBox_17.setText(_translate("MainWindow", "select"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_18.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_18.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_19.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_19.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_67.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_68.setText(_translate("MainWindow", "1.8"))
        self.checkBox_18.setText(_translate("MainWindow", "select"))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_21.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_21.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_21.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_22.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_22.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_69.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_70.setText(_translate("MainWindow", "1.8"))
        self.checkBox_19.setText(_translate("MainWindow", "select"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_20.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_37.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_37.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_37.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_37.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_71.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_72.setText(_translate("MainWindow", "1.8"))
        self.label_36.setText(_translate("MainWindow", "delay"))
        self.label_40.setText(_translate("MainWindow", "rail"))
        self.label_41.setText(_translate("MainWindow", "data"))
        self.label_39.setText(_translate("MainWindow", "command"))
        self.label_37.setText(_translate("MainWindow", "Loop"))
        self.lineEdit_58.setText(_translate("MainWindow", "1"))
        self.label_38.setText(_translate("MainWindow", "times"))
        self.pushButton_12.setText(_translate("MainWindow", "Abort"))
        self.pushButton_13.setText(_translate("MainWindow", "Run"))
        self.checkBox_10.setText(_translate("MainWindow", "select"))
        self.comboBox_23.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_23.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_23.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_23.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_24.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_24.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_24.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_24.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_44.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_45.setText(_translate("MainWindow", "1.8"))
        self.checkBox_11.setText(_translate("MainWindow", "select"))
        self.comboBox_25.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_25.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_25.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_25.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_26.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_26.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_26.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_26.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_46.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_47.setText(_translate("MainWindow", "1.8"))
        self.checkBox_12.setText(_translate("MainWindow", "select"))
        self.comboBox_27.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_27.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_27.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_27.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_28.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_28.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_28.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_28.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_48.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_49.setText(_translate("MainWindow", "1.8"))
        self.checkBox_13.setText(_translate("MainWindow", "select"))
        self.comboBox_29.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_29.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_29.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_29.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_30.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_30.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_30.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_30.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_50.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_51.setText(_translate("MainWindow", "1.8"))
        self.checkBox_14.setText(_translate("MainWindow", "select"))
        self.comboBox_31.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_31.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_31.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_31.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_32.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_32.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_32.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_32.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_52.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_53.setText(_translate("MainWindow", "1.8"))
        self.checkBox_15.setText(_translate("MainWindow", "select"))
        self.comboBox_33.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_33.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_33.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_33.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_34.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_34.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_34.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_34.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_54.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_55.setText(_translate("MainWindow", "1.8"))
        self.checkBox_16.setText(_translate("MainWindow", "select"))
        self.comboBox_35.setItemText(0, _translate("MainWindow", "VCCIN"))
        self.comboBox_35.setItemText(1, _translate("MainWindow", "VCCINFAON"))
        self.comboBox_35.setItemText(2, _translate("MainWindow", "VCCFA_EHV"))
        self.comboBox_35.setItemText(3, _translate("MainWindow", "VCCFA_EHV_FIVRA"))
        self.comboBox_36.setItemText(0, _translate("MainWindow", "SetWP1"))
        self.comboBox_36.setItemText(1, _translate("MainWindow", "SetWP2"))
        self.comboBox_36.setItemText(2, _translate("MainWindow", "GetReg"))
        self.comboBox_36.setItemText(3, _translate("MainWindow", "SetPS"))
        self.lineEdit_56.setText(_translate("MainWindow", "1.8"))
        self.lineEdit_57.setText(_translate("MainWindow", "1.8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "SetWP"))
        self.menu2020_08_22.setTitle(_translate("MainWindow", "About"))
        self.action2020_10.setText(_translate("MainWindow", "2020.10"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
